#!/usr/bin/env python3
"""
VA21 OS - Project Builder for Coding IDE
==========================================

Om Vinayaka - Building complete applications with intelligent assistance.

The Project Builder provides:
- Full-stack project scaffolding
- Template generation for various project types
- Build system setup and configuration
- Dependency management
- File structure creation

This component creates complete, runnable project structures
based on the suggestions from the Suggest Engine and the
architecture planned by the Multi-Agent Orchestrator.

Copyright (c) 2024-2025 Prayaga Vaibhav. All rights reserved.
"""

import os
import json
import shutil
import subprocess
from datetime import datetime
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path


class ProjectType(Enum):
    """Types of projects that can be built."""
    WEB_FRONTEND = "web_frontend"
    WEB_BACKEND = "web_backend"
    WEB_FULLSTACK = "web_fullstack"
    MOBILE_APP = "mobile_app"
    DESKTOP_APP = "desktop_app"
    CLI_TOOL = "cli_tool"
    API_SERVICE = "api_service"
    LIBRARY = "library"
    ML_PROJECT = "ml_project"


@dataclass
class ProjectConfig:
    """Configuration for a project."""
    name: str
    description: str
    project_type: ProjectType
    language: str
    framework: Optional[str]
    database: Optional[str]
    features: List[str]
    target_os: List[str]
    author: Optional[str] = None
    version: str = "0.1.0"
    license: str = "MIT"


@dataclass
class GeneratedFile:
    """A file generated by the builder."""
    path: str
    content: str
    is_template: bool = False


@dataclass
class ProjectStructure:
    """Complete project structure."""
    root_path: str
    config: ProjectConfig
    files: List[GeneratedFile] = field(default_factory=list)
    directories: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.now)


# Project templates
TEMPLATES = {
    # Python FastAPI backend
    "python_fastapi": {
        "directories": [
            "src", "src/api", "src/api/routes", "src/core",
            "src/db", "src/models", "src/schemas", "src/services",
            "tests", "tests/api", "tests/unit"
        ],
        "files": {
            "README.md": '''# {name}

{description}

## Setup

```bash
# Create virtual environment
python -m venv venv
source venv/bin/activate  # Linux/Mac
# venv\\Scripts\\activate  # Windows

# Install dependencies
pip install -r requirements.txt

# Run the application
uvicorn src.main:app --reload
```

## API Documentation

Once running, visit:
- Swagger UI: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc

## License

{license}
''',
            "requirements.txt": '''fastapi>=0.104.0
uvicorn[standard]>=0.24.0
pydantic>=2.5.0
python-dotenv>=1.0.0
sqlalchemy>=2.0.0
alembic>=1.12.0
pytest>=7.4.0
httpx>=0.25.0
''',
            "src/__init__.py": '',
            "src/main.py": '''"""
{name} - Main Application Entry Point

Om Vinayaka - May obstacles be removed from your coding journey.
Generated by VA21 Coding IDE
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from src.api.routes import router as api_router
from src.core.config import settings

app = FastAPI(
    title="{name}",
    description="{description}",
    version="{version}",
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include API routes
app.include_router(api_router, prefix="/api/v1")


@app.get("/")
async def root():
    """Health check endpoint."""
    return {{"status": "healthy", "app": "{name}"}}


@app.get("/health")
async def health_check():
    """Detailed health check."""
    return {{
        "status": "healthy",
        "version": "{version}",
        "service": "{name}"
    }}
''',
            "src/core/__init__.py": '',
            "src/core/config.py": '''"""Application configuration."""

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """Application settings."""
    
    APP_NAME: str = "{name}"
    DEBUG: bool = False
    DATABASE_URL: str = "sqlite:///./app.db"
    SECRET_KEY: str = "change-me-in-production"
    
    class Config:
        env_file = ".env"


settings = Settings()
''',
            "src/api/__init__.py": '',
            "src/api/routes/__init__.py": '''"""API Routes."""

from fastapi import APIRouter

router = APIRouter()


@router.get("/")
async def api_root():
    """API root endpoint."""
    return {{"message": "Welcome to {name} API"}}
''',
            "src/models/__init__.py": '',
            "src/schemas/__init__.py": '',
            "src/services/__init__.py": '',
            "src/db/__init__.py": '',
            "tests/__init__.py": '',
            "tests/test_main.py": '''"""Tests for main application."""

import pytest
from fastapi.testclient import TestClient

from src.main import app

client = TestClient(app)


def test_root():
    """Test root endpoint."""
    response = client.get("/")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"


def test_health():
    """Test health endpoint."""
    response = client.get("/health")
    assert response.status_code == 200
    assert "version" in response.json()
''',
            ".env.example": '''# Environment Variables
DEBUG=false
DATABASE_URL=sqlite:///./app.db
SECRET_KEY=your-secret-key-here
''',
            ".gitignore": '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
.env

# IDE
.idea/
.vscode/
*.swp
*.swo

# Testing
.pytest_cache/
htmlcov/
.coverage

# Build
dist/
build/
*.egg-info/
'''
        }
    },
    
    # Node.js Express backend
    "node_express": {
        "directories": [
            "src", "src/routes", "src/controllers", "src/middleware",
            "src/models", "src/services", "src/utils", "src/config",
            "tests"
        ],
        "files": {
            "README.md": '''# {name}

{description}

## Setup

```bash
# Install dependencies
npm install

# Run in development
npm run dev

# Run in production
npm start

# Run tests
npm test
```

## API Endpoints

- GET / - Health check
- GET /api - API root

## License

{license}
''',
            "package.json": '''{
  "name": "{name_slug}",
  "version": "{version}",
  "description": "{description}",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js",
    "test": "jest",
    "lint": "eslint src/"
  },
  "author": "{author}",
  "license": "{license}",
  "dependencies": {
    "express": "^4.18.2",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0"
  },
  "devDependencies": {
    "jest": "^29.7.0",
    "nodemon": "^3.0.2",
    "eslint": "^8.55.0",
    "supertest": "^6.3.3"
  }
}
''',
            "src/index.js": '''/**
 * {name} - Main Application Entry Point
 * 
 * Om Vinayaka - May obstacles be removed from your coding journey.
 * Generated by VA21 Coding IDE
 */

require('dotenv').config();

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');

const routes = require('./routes');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Routes
app.use('/api', routes);

// Health check
app.get('/', (req, res) => {
  res.json({ status: 'healthy', app: '{name}' });
});

app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    version: '{version}',
    service: '{name}',
    uptime: process.uptime()
  });
});

// Error handler
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 {name} running on port ${{PORT}}`);
});

module.exports = app;
''',
            "src/routes/index.js": '''/**
 * API Routes
 */

const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  res.json({ message: 'Welcome to {name} API' });
});

module.exports = router;
''',
            "src/config/index.js": '''/**
 * Application Configuration
 */

module.exports = {
  port: process.env.PORT || 3000,
  nodeEnv: process.env.NODE_ENV || 'development',
  // Add more configuration as needed
};
''',
            "src/controllers/.gitkeep": '',
            "src/middleware/.gitkeep": '',
            "src/models/.gitkeep": '',
            "src/services/.gitkeep": '',
            "src/utils/.gitkeep": '',
            "tests/app.test.js": '''/**
 * Application Tests
 */

const request = require('supertest');
const app = require('../src/index');

describe('GET /', () => {
  it('should return health status', async () => {
    const res = await request(app).get('/');
    expect(res.statusCode).toBe(200);
    expect(res.body.status).toBe('healthy');
  });
});

describe('GET /api', () => {
  it('should return welcome message', async () => {
    const res = await request(app).get('/api');
    expect(res.statusCode).toBe(200);
    expect(res.body.message).toContain('Welcome');
  });
});
''',
            ".env.example": '''# Environment Variables
PORT=3000
NODE_ENV=development
''',
            ".gitignore": '''# Dependencies
node_modules/

# Environment
.env

# Logs
*.log
npm-debug.log*

# IDE
.idea/
.vscode/
*.swp

# Testing
coverage/

# Build
dist/
build/
'''
        }
    },
    
    # React frontend
    "react_frontend": {
        "directories": [
            "src", "src/components", "src/components/common",
            "src/pages", "src/hooks", "src/services", "src/utils",
            "src/styles", "public"
        ],
        "files": {
            "README.md": '''# {name}

{description}

## Setup

```bash
# Install dependencies
npm install

# Run development server
npm run dev

# Build for production
npm run build

# Run tests
npm test
```

## License

{license}
''',
            "package.json": '''{
  "name": "{name_slug}",
  "version": "{version}",
  "description": "{description}",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "vitest",
    "lint": "eslint src/"
  },
  "author": "{author}",
  "license": "{license}",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.21.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.2.1",
    "vite": "^5.0.8",
    "vitest": "^1.1.0",
    "eslint": "^8.55.0",
    "eslint-plugin-react": "^7.33.2"
  }
}
''',
            "vite.config.js": '''import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
  },
});
''',
            "index.html": '''<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
''',
            "src/main.jsx": '''/**
 * {name} - Main Entry Point
 * 
 * Om Vinayaka - May obstacles be removed from your coding journey.
 * Generated by VA21 Coding IDE
 */

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles/index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
''',
            "src/App.jsx": '''/**
 * Main App Component
 */

import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Home from './pages/Home';
import './styles/App.css';

function App() {
  return (
    <BrowserRouter>
      <div className="app">
        <Routes>
          <Route path="/" element={<Home />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

export default App;
''',
            "src/pages/Home.jsx": '''/**
 * Home Page
 */

import React from 'react';

function Home() {
  return (
    <div className="home">
      <header className="header">
        <h1>{name}</h1>
        <p>{description}</p>
      </header>
      <main className="main">
        <p>Welcome to your new React application!</p>
        <p>Built with VA21 Coding IDE</p>
      </main>
    </div>
  );
}

export default Home;
''',
            "src/components/common/.gitkeep": '',
            "src/hooks/.gitkeep": '',
            "src/services/.gitkeep": '',
            "src/utils/.gitkeep": '',
            "src/styles/index.css": '''/* Global Styles */

:root {
  --primary-color: #646cff;
  --background-color: #242424;
  --text-color: #ffffff;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
  background-color: var(--background-color);
  color: var(--text-color);
  min-height: 100vh;
}

a {
  color: var(--primary-color);
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
''',
            "src/styles/App.css": '''/* App Styles */

.app {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.header {
  text-align: center;
  margin-bottom: 2rem;
}

.header h1 {
  font-size: 2.5rem;
  margin-bottom: 0.5rem;
}

.header p {
  color: #888;
}

.main {
  text-align: center;
}
''',
            "public/favicon.svg": '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <text x="50%" y="50%" font-size="80" text-anchor="middle" dy=".35em">🚀</text>
</svg>
''',
            ".gitignore": '''# Dependencies
node_modules/

# Build
dist/
build/

# Environment
.env
.env.local

# IDE
.idea/
.vscode/
*.swp

# Testing
coverage/

# Logs
*.log
'''
        }
    },
    
    # Python CLI tool
    "python_cli": {
        "directories": [
            "src", "src/commands", "tests"
        ],
        "files": {
            "README.md": '''# {name}

{description}

## Installation

```bash
pip install -e .
```

## Usage

```bash
{name_slug} --help
```

## Development

```bash
# Install dev dependencies
pip install -e ".[dev]"

# Run tests
pytest
```

## License

{license}
''',
            "pyproject.toml": '''[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{name_slug}"
version = "{version}"
description = "{description}"
authors = [{{name = "{author}", email = "author@example.com"}}]
license = {{text = "{license}"}}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
]

[project.scripts]
{name_slug} = "src.main:cli"
''',
            "src/__init__.py": '''"""
{name}

{description}
"""

__version__ = "{version}"
''',
            "src/main.py": '''"""
{name} - CLI Entry Point

Om Vinayaka - May obstacles be removed from your coding journey.
Generated by VA21 Coding IDE
"""

import click
from rich.console import Console

console = Console()


@click.group()
@click.version_option()
def cli():
    """{description}"""
    pass


@cli.command()
@click.argument('name', default='World')
def hello(name):
    """Say hello."""
    console.print(f"[bold green]Hello, {{name}}![/bold green]")


@cli.command()
def info():
    """Show application info."""
    console.print("[bold]{name}[/bold]")
    console.print("{description}")
    console.print(f"Version: {version}")


if __name__ == '__main__':
    cli()
''',
            "src/commands/__init__.py": '',
            "tests/__init__.py": '',
            "tests/test_cli.py": '''"""Tests for CLI."""

from click.testing import CliRunner
from src.main import cli


def test_hello():
    """Test hello command."""
    runner = CliRunner()
    result = runner.invoke(cli, ['hello', 'Test'])
    assert result.exit_code == 0
    assert 'Hello' in result.output


def test_info():
    """Test info command."""
    runner = CliRunner()
    result = runner.invoke(cli, ['info'])
    assert result.exit_code == 0
''',
            ".gitignore": '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
.env

# Build
dist/
build/
*.egg-info/

# IDE
.idea/
.vscode/
*.swp

# Testing
.pytest_cache/
.coverage
htmlcov/
'''
        }
    }
}


class ProjectBuilder:
    """
    VA21 Coding IDE Project Builder
    
    Creates complete, runnable project structures based on
    configuration and templates. Integrates with:
    
    - Suggest Engine for technology recommendations
    - Multi-Agent Orchestrator for complex projects
    - AI Helper for intelligent code generation
    
    Supports various project types:
    - Web frontends (React, Vue, etc.)
    - Web backends (FastAPI, Express, etc.)
    - Full-stack applications
    - CLI tools
    - Mobile apps
    - And more...
    """
    
    VERSION = "1.0.0"
    DEFAULT_PROJECTS_PATH = os.path.expanduser("~/va21_projects")
    
    def __init__(self, projects_path: str = None):
        """
        Initialize the project builder.
        
        Args:
            projects_path: Path where projects will be created
        """
        self.projects_path = projects_path or self.DEFAULT_PROJECTS_PATH
        os.makedirs(self.projects_path, exist_ok=True)
        
        self.templates = TEMPLATES
        self.created_projects: List[ProjectStructure] = []
        
        print(f"[ProjectBuilder] Initialized v{self.VERSION}")
        print(f"[ProjectBuilder] Projects path: {self.projects_path}")
    
    def get_template(self, template_name: str) -> Optional[Dict]:
        """Get a project template by name."""
        return self.templates.get(template_name)
    
    def list_templates(self) -> List[str]:
        """List available templates."""
        return list(self.templates.keys())
    
    def create_project(self, config: ProjectConfig, 
                       template_name: str = None) -> ProjectStructure:
        """
        Create a new project.
        
        Args:
            config: Project configuration
            template_name: Optional specific template to use
            
        Returns:
            ProjectStructure with created files
        """
        # Determine template to use
        if not template_name:
            template_name = self._select_template(config)
        
        template = self.templates.get(template_name)
        if not template:
            raise ValueError(f"Template '{template_name}' not found")
        
        # Create project structure
        project_root = os.path.join(self.projects_path, self._slugify(config.name))
        
        # Check if project already exists
        if os.path.exists(project_root):
            # Add timestamp to make unique
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            project_root = f"{project_root}_{timestamp}"
        
        structure = ProjectStructure(
            root_path=project_root,
            config=config
        )
        
        # Create directories
        os.makedirs(project_root, exist_ok=True)
        for directory in template.get("directories", []):
            dir_path = os.path.join(project_root, directory)
            os.makedirs(dir_path, exist_ok=True)
            structure.directories.append(dir_path)
        
        # Create files
        template_vars = self._get_template_vars(config)
        
        for file_path, content in template.get("files", {}).items():
            full_path = os.path.join(project_root, file_path)
            
            # Create parent directories if needed
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            
            # Format content with template variables
            formatted_content = content.format(**template_vars)
            
            # Write file
            with open(full_path, 'w') as f:
                f.write(formatted_content)
            
            structure.files.append(GeneratedFile(
                path=full_path,
                content=formatted_content,
                is_template=True
            ))
        
        self.created_projects.append(structure)
        
        print(f"[ProjectBuilder] Created project: {config.name}")
        print(f"[ProjectBuilder] Location: {project_root}")
        print(f"[ProjectBuilder] Files: {len(structure.files)}")
        
        return structure
    
    def _select_template(self, config: ProjectConfig) -> str:
        """Select appropriate template based on config."""
        language = config.language.lower()
        framework = (config.framework or "").lower()
        
        # Map to template
        if language == "python":
            if framework in ["fastapi", "flask"]:
                return "python_fastapi"
            elif config.project_type == ProjectType.CLI_TOOL:
                return "python_cli"
            else:
                return "python_fastapi"
        
        elif language in ["javascript", "typescript"]:
            if framework in ["react", "vue", "angular", "svelte"]:
                return "react_frontend"
            elif framework in ["express", "node", "nestjs"]:
                return "node_express"
            else:
                return "node_express"
        
        # Default
        return "python_fastapi"
    
    def _slugify(self, name: str) -> str:
        """Convert name to slug."""
        return name.lower().replace(" ", "_").replace("-", "_")
    
    def _get_template_vars(self, config: ProjectConfig) -> Dict[str, str]:
        """Get variables for template substitution."""
        return {
            "name": config.name,
            "name_slug": self._slugify(config.name),
            "description": config.description or "A VA21 Coding IDE project",
            "version": config.version,
            "author": config.author or "VA21 User",
            "license": config.license,
            "language": config.language,
            "framework": config.framework or "",
        }
    
    def create_from_suggestion(self, suggestion_report: Dict) -> ProjectStructure:
        """
        Create a project from a suggestion engine report.
        
        Args:
            suggestion_report: Report from SuggestEngine
            
        Returns:
            ProjectStructure
        """
        # Extract configuration from suggestion
        requirements = suggestion_report.get("parsed_requirements", {})
        top_language = suggestion_report.get("recommendation", {}).get("primary_language", "Python")
        top_stack = suggestion_report.get("stack_suggestions", [{}])[0]
        
        config = ProjectConfig(
            name=f"{requirements.get('app_type', 'app').replace('_', ' ').title()} Project",
            description=suggestion_report.get("original_input", ""),
            project_type=self._map_app_type(requirements.get("app_type", "web_app")),
            language=top_language,
            framework=top_stack.get("frontend") or top_stack.get("backend"),
            database=top_stack.get("database"),
            features=requirements.get("features", []),
            target_os=requirements.get("target_os", ["cross_platform"])
        )
        
        return self.create_project(config)
    
    def _map_app_type(self, app_type: str) -> ProjectType:
        """Map app type string to ProjectType enum."""
        mapping = {
            "web_app": ProjectType.WEB_FULLSTACK,
            "api_service": ProjectType.API_SERVICE,
            "mobile_app": ProjectType.MOBILE_APP,
            "desktop_app": ProjectType.DESKTOP_APP,
            "cli_tool": ProjectType.CLI_TOOL,
            "ml_ai": ProjectType.ML_PROJECT,
        }
        return mapping.get(app_type, ProjectType.WEB_FULLSTACK)
    
    def install_dependencies(self, project_path: str) -> bool:
        """
        Install dependencies for a project.
        
        Args:
            project_path: Path to the project
            
        Returns:
            True if successful
        """
        try:
            # Check for package.json (Node.js)
            package_json = os.path.join(project_path, "package.json")
            if os.path.exists(package_json):
                print(f"[ProjectBuilder] Installing npm dependencies...")
                subprocess.run(
                    ["npm", "install"],
                    cwd=project_path,
                    check=True,
                    capture_output=True
                )
                print(f"[ProjectBuilder] npm install complete")
                return True
            
            # Check for requirements.txt (Python)
            requirements_txt = os.path.join(project_path, "requirements.txt")
            if os.path.exists(requirements_txt):
                print(f"[ProjectBuilder] Installing pip dependencies...")
                subprocess.run(
                    ["pip", "install", "-r", "requirements.txt"],
                    cwd=project_path,
                    check=True,
                    capture_output=True
                )
                print(f"[ProjectBuilder] pip install complete")
                return True
            
            # Check for pyproject.toml (Python)
            pyproject = os.path.join(project_path, "pyproject.toml")
            if os.path.exists(pyproject):
                print(f"[ProjectBuilder] Installing with pip editable mode...")
                subprocess.run(
                    ["pip", "install", "-e", "."],
                    cwd=project_path,
                    check=True,
                    capture_output=True
                )
                print(f"[ProjectBuilder] pip install complete")
                return True
            
            print(f"[ProjectBuilder] No dependency file found")
            return False
            
        except subprocess.CalledProcessError as e:
            print(f"[ProjectBuilder] Dependency install failed: {e}")
            return False
        except FileNotFoundError as e:
            print(f"[ProjectBuilder] Command not found: {e}")
            return False
    
    def run_project(self, project_path: str, dev: bool = True) -> subprocess.Popen:
        """
        Run a project in development mode.
        
        Args:
            project_path: Path to the project
            dev: Whether to run in development mode
            
        Returns:
            Subprocess handle
        """
        # Check for package.json (Node.js)
        package_json = os.path.join(project_path, "package.json")
        if os.path.exists(package_json):
            cmd = ["npm", "run", "dev" if dev else "start"]
            return subprocess.Popen(cmd, cwd=project_path)
        
        # Check for Python (uvicorn)
        main_py = os.path.join(project_path, "src", "main.py")
        if os.path.exists(main_py):
            cmd = ["uvicorn", "src.main:app", "--reload"] if dev else ["uvicorn", "src.main:app"]
            return subprocess.Popen(cmd, cwd=project_path)
        
        raise RuntimeError("Could not determine how to run this project")
    
    def get_project_info(self, project_path: str) -> Dict:
        """Get information about a project."""
        info = {
            "path": project_path,
            "exists": os.path.exists(project_path),
            "type": None,
            "files_count": 0,
            "dependencies_installed": False
        }
        
        if not info["exists"]:
            return info
        
        # Count files
        for root, dirs, files in os.walk(project_path):
            # Skip node_modules and venv
            dirs[:] = [d for d in dirs if d not in ['node_modules', 'venv', '.git', '__pycache__']]
            info["files_count"] += len(files)
        
        # Detect type
        if os.path.exists(os.path.join(project_path, "package.json")):
            info["type"] = "node"
            info["dependencies_installed"] = os.path.exists(os.path.join(project_path, "node_modules"))
        elif os.path.exists(os.path.join(project_path, "requirements.txt")):
            info["type"] = "python"
            # Check for venv
            info["dependencies_installed"] = os.path.exists(os.path.join(project_path, "venv"))
        elif os.path.exists(os.path.join(project_path, "pyproject.toml")):
            info["type"] = "python"
        
        return info
    
    def list_created_projects(self) -> List[Dict]:
        """List all created projects."""
        return [
            {
                "name": p.config.name,
                "path": p.root_path,
                "type": p.config.project_type.value,
                "language": p.config.language,
                "created_at": p.created_at.isoformat()
            }
            for p in self.created_projects
        ]


# Singleton instance
_project_builder_instance = None


def get_project_builder(projects_path: str = None) -> ProjectBuilder:
    """Get or create the ProjectBuilder singleton."""
    global _project_builder_instance
    if _project_builder_instance is None:
        _project_builder_instance = ProjectBuilder(projects_path)
    return _project_builder_instance


# CLI interface
def main():
    """CLI interface for testing the project builder."""
    builder = get_project_builder()
    
    print("=" * 60)
    print("VA21 Coding IDE - Project Builder")
    print("=" * 60)
    
    print("\n📋 Available Templates:")
    for template in builder.list_templates():
        print(f"  • {template}")
    
    # Create a test project
    print("\n" + "=" * 60)
    print("Creating test project...")
    print("=" * 60)
    
    config = ProjectConfig(
        name="Test Web App",
        description="A test web application created by VA21 Coding IDE",
        project_type=ProjectType.WEB_BACKEND,
        language="Python",
        framework="FastAPI",
        database="PostgreSQL",
        features=["authentication", "api"],
        target_os=["linux"]
    )
    
    structure = builder.create_project(config)
    
    print(f"\n✅ Project created!")
    print(f"   Path: {structure.root_path}")
    print(f"   Files: {len(structure.files)}")
    print(f"   Directories: {len(structure.directories)}")
    
    print("\n📁 Project structure:")
    for file in structure.files[:10]:
        rel_path = os.path.relpath(file.path, structure.root_path)
        print(f"   {rel_path}")
    if len(structure.files) > 10:
        print(f"   ... and {len(structure.files) - 10} more files")


if __name__ == "__main__":
    main()
